### ISSUE TITLE
Update eslint-plugin-react and eslint-config-xo-react

### ISSUE THREAD

**Issue by zckrs** [FountainJS/generator-fountain-react#16]
We should update these deps.

But a problem exist. 'eslint-config-xo-react' define indent for JSX with tab except we use 'eslint-config-xo-space' with '.editorconfig' who set indent with space. So we can't insert tab and space in the same component file.

**Comment by zckrs** [comment]
Related https://github.com/sindresorhus/eslint-config-xo-react/issues/7

**Comment by zckrs** [comment]
Alternative walkthrough:

reset rule in package.json

```
"rules": {
      "react/jsx-indent-props": [ 2, 2 ],
      "react/jsx-indent": [ 2, 2 ]
    }
```

**Comment by zckrs** [comment]
https://github.com/zckrs/eslint-config-xo-react-space

**Comment by Swiip** [comment]
you did it ^^

**Comment by zckrs** [comment]
Yep but the package is already taken on NPM https://www.npmjs.com/package/eslint-config-xo-react-space and he doesn't use `extend` in conf :( 

https://github.com/akameco/eslint-config-xo-react-space/blob/master/index.js#L2

vs

https://github.com/zckrs/eslint-config-xo-react-space/blob/master/index.js#L3
