### ISSUE TITLE
How to cancel eslint syntax check

### ISSUE THREAD

**Issue by tanxu** [FountainJS/generator-fountain-react#60]
RT

**Comment by Swiip** [comment]
If you use Webpack, comment the preLoader part of the conf. If not, comment the eslint part of `gulp_tasks/scripts.js`.

**Comment by through-a-haze** [comment]
How can  I change eslint checking settings?

**Comment by septagram** [comment]
@through-a-haze Stumbled on this also having this exact problem. At first I passed `options` to `eslint-loader` in `conf/webpack-conf.js`, but it appears the right place for that is actually `package.json`. At the bottom of the file there's a section `"eslintConfig"` with some default settings. You can modify the rules there as you wish by changing the list of default configs in the `"extends"` subsection or by adding a `"rules"` subsection with your custom rules, for example:

    "eslintConfig": {
      "root": true,
      "env": {
        "browser": true,
        "jasmine": true
      },
      "extends": [
        "xo-react/space",
        "xo-space/esnext"
      ],
      "parser": "babel-eslint",
      "rules": {
        "semi": 0
      }
    }

Yes, I'm in the [ASI](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) camp.
